# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: ICAD to MQTT Bridge
version: "2.0.0"
slug: icad2mqtt
description: Fetch active CAD calls from 911events and publish to MQTT
url: "https://github.com/JustBeanie/icad2mqtt"
image: ghcr.io/justbeanie/icad2mqtt
arch:
  - aarch64
  - amd64
startup: application
boot: auto
hassio_api: false
hassio_role: default
host_network: false
services:
  - mqtt:want
options:
  mqtt_broker: "tcp://localhost:1883"
  mqtt_topic: "911/cad/events"
  mqtt_base_topic: "911/cad"
  publish_raw: true
  ha_discovery: false
  mqtt_username: ""
  mqtt_password: ""
  poll_interval: 60
schema:
  mqtt_broker: "str"
  mqtt_topic: "str?"
  mqtt_base_topic: "str?"
  publish_raw: "bool?"
  ha_discovery: "bool?"
  mqtt_username: "str?"
  mqtt_password: "password?"
  poll_interval: "int?"
